add webhook notify in ci

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -10,6 +10,20 @@ env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
+    begin-notification:
+      runs-on: ubuntu-latest
+      steps:
+        - name: release/checkout-repo
+          uses: actions/checkout@v3
+        - name: release/notify-channel
+          run: |
+            jq --null-input \
+            --arg icon_url "https://infomaniak.kchat.infomaniak.com/static/emoji/kchat.png" \
+            --arg username "DesktopReleaseBot" \
+            --arg text "[$(jq -r .version package.json)] Release for desktop app started from GitHub, it should take about 30 minutes to complete." \
+            '{"username":$username,"icon_url": $icon_url, "text": $text }' > /tmp/webhook-data.json
+            curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.RELEASE_WEBHOOK_URL }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
+
     create-release:
         runs-on: ubuntu-latest
         outputs:
@@ -258,3 +272,22 @@ jobs:
                   asset_path: "./artifacts/kchat-desktop_${{ github.ref_name }}-1_arm64.deb"
                   asset_name: "kchat-desktop_${{ github.ref_name }}-1_arm64.deb"
                   asset_content_type: application/octet-stream
+
+    end-notification:
+      runs-on: ubuntu-latest
+      needs:
+        - upload-to-github
+      steps:
+        - name: release/checkout-repo
+          uses: actions/checkout@v3
+          with:
+            fetch-depth: 0
+        - name: release/notify-channel
+          run: |
+            git fetch --all
+            jq --null-input \
+            --arg icon_url "https://infomaniak.kchat.infomaniak.com/static/emoji/kchat.png" \
+            --arg username "DesktopReleaseBot" \
+            --arg text "$(bash -x scripts/generate_release_post.sh $(jq -r .version package.json))" \
+            '{"username":$username,"icon_url": $icon_url, "text": $text }' > /tmp/webhook-data.json
+            curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.RELEASE_WEBHOOK_URL }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
